dfinity/icp-js-core

packages/candid/src/idl.ts
The bug was `IDL.Nat64.covariant(0n) == false`, but it should be true.
=> fix: Fix an IDL bug in using FixedNat with BigInt

demos/ledgerhq/src/main.js, package-lock.json, packages/identity-ledgerhq/.gitignore, packages/identity-ledgerhq/README.md, packages/identity-ledgerhq/package.json, packages/identity-ledgerhq/src/identity/ledger.ts, packages/identity-ledgerhq/src/identity/ledger_hq__hw_transport_webhid.d.ts
There seems to be problems with the latest Chrome and WebUSB API, so
this is a test to mitigate those issues. See links below for more
information:
https://support.ledger.com/hc/en-us/articles/360020871157-Connection-issues-with-MetaMask-
https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md
https://www.xda-developers.com/google-disables-chrome-webusb/
=> refactor: move ledgerhq identity to using webhid

tsconfig.json
also allows you to do unallowed things like modifying window for tests
=> chore: excludes tests from tsconfig build process

packages/identity/src/identity/der.ts, packages/identity/src/identity/ed25519.test.ts, packages/identity/src/identity/ed25519.ts, packages/identity/src/identity/webauthn.ts, packages/identity/src/index.ts
This is needed to be able to use the WebAuthn identity with public keys larger than 127 bytes. It should be a non-breaking change, unless someone relied on identity creation failing for larger keys.
So far this library hardcoded the DER prefixes, which works until the payload becomes larger than 127 bytes, as you need to encode the length of sequences and bitstrings according to the "Definite scheme" as described here: https://en.wikipedia.org/wiki/X.690#Definite_form
Along the same line we need to unwrap DER in other places, which runs into the same issue. So far this library pretends we can always slice off a fixed amount of bytes at the front to remove the DER wrapper, but we actually need to parse just enough structure to know how many bytes are used to encode lengths.
=> fix: Implements DER wrapping and unwrapping

apps/sw-cert/src/sw/http_request.ts
This change makes the service worker return the error message as the
response body if a fetch failed.  This should give us more insight
into why some people can't access nns and identity.
=> chore: improve error reporting in service worker

packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
Ensures that all nested `bigints` are stringified.
Previously, would simply throw a `TypeError: Do not know how to serialize a BigInt` during encode or decode errors
=> fix(candid): Stringify all bigints

package-lock.json, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
I encountered a bug trying to intialize an authClient using a Plug identity, where I was still getting an anonymous identity back. This will properly use the option we pass to `AuthClient.create`
=> fix: auth-client identity option

packages/principal/src/index.ts
This prints the original value, which (I think) is more useful to the
user when trying to figure out why `toText()` couldn't create a
`Principal`.
=> feat: Clarify fromText() sanity check

apps/sw-cert/src/sw/http_request.ts
Now, we are not able to make requests  to `raw.ic0.app` from the frontend, where the service worker is already installed.
Steps for reproduce:
- go to any app (for example go to OpenChat `https://7e6iv-biaaa-aaaaf-aaada-cai.ic0.app/`)
- open the console
- we make a request to the same canister in raw domain zone `fetch('https://7e6iv-biaaa-aaaaf-aaada-cai.raw.ic0.app')`
- got 404 error
[Link to the forum topic](https://forum.dfinity.org/t/is-it-possible-to-make-raw-ic0-app-calls-from-ic0-app-and-reverse/8224)
PS. Perhaps this solution is not the best, but let's find the right one.
=> fix: Make requests from ic0.app domain to raw.ic0.app

package.json, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/errors.ts
A step toward idle timeouts in auth-client
=> feat: httpagent should allow its identity to be invalidated

packages/agent/src/agent/http/index.ts
Problem:
When `@dfinity/agent@0.10.2` used by boundary node service-worker, then `this._fetch(...)` throws error `Failed to fetch response: TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Illegal invocation`
Its caused by missing `.bind(...)` in fetch gettter
=> fix: fetch binding

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/types.ts
The makeNonce method ended up returning the same value: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
There were a couple problems:
- DateTime.now() * 100,000 didn't extend any values into the high 64 bits
- view.setBigUint64(1, value) sets 8 bytes starting at byte offset 1, not the address of the second biguint64
The end result was that only the first byte of the nonce would have a nonzero value.
This change puts the current time in the high 64 bits (the first several bytes are still zero), and fills the low 64 bits with random data.
Fixes https://dfinity.atlassian.net/browse/SDK-396
The first commit in this branch added a unit test, the failure of which demonstrates that the nonce values were not unique.
=> fix: make makeNonce return unique random values

packages/auth-client/src/index.ts
This adds a debug message in case II is replying with a bad origin.
=> feat: warn on bad origin

docs/generated/changelog.html, packages/auth-client/README.md, packages/auth-client/src/idleManager.test.ts, packages/auth-client/src/idleManager.ts, packages/auth-client/src/index.ts
Per security requests, reduces the default delegation expiration from 24 hours to 8. 
Also cleans up and adds additional documentation
=> chore: reduces default delegation expiration to 8 hours

bin/version.ts, docs/generated/changelog.html, package-lock.json, package.json
=> fix: versioning script now updates package.json

demos/ledgerhq/src/main.js, docs/generated/changelog.html, e2e/node/basic/counter.test.ts, e2e/node/canisters/counter.ts, e2e/node/utils/agent.ts, packages/agent/src/actor.test.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
HttpAgent will now provide a unique nonce in calls to ensure that the replica treats each call as unique.
Tested in our integration test suie
=> feat: generate nonce for HttpAgent calls

packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
This extends the `AuthClientLoginOptions` interface to include a configuration string used to pass to the `window.open` function. Using this string allows the user to configure the opened II authentication window.
**Tested by locally applying a sample configuration and updating the test suite**:
=> feat: add window config string

demos/ledgerhq/package.json, demos/sample-javascript/package.json, e2e/node/package.json, package-lock.json, package.json, packages/agent/package.json, packages/auth-client/package.json, packages/authentication/package.json, packages/candid/package.json, packages/identity-ledgerhq/package.json, packages/identity/package.json, packages/principal/package.json
Releases 0.11.0 - the idleManager release. 
upgrading to this version will change default behavior in `@dfinity/auth-client`.
* default delegation expiration is now 8 hours if not specified
* Idle manager will now log users out after 10 minutes
* idle manager can be disabled and its timeout is also configurable
* HttpAgent now makes calls using a nonce
* HttpAgent identities can be invalidated or replaced
=> chore: release v.0.11.0

packages/agent/README.md, packages/auth-client/README.md, packages/authentication/README.md, packages/candid/README.md, packages/identity/README.md, packages/principal/README.md
Replaces a redirect via peacock.dev to our docs with an IC-native option.
=> chore: replaces peacock.dev redirects with agent-js.icp.host

packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
Improve candid decoding to no longer lose type information for Functions and Services. This is required due to the recent introduction of `IDL.Unknown`.
Unit test are covering this behavior.
=> feat: Retain type information for functions and services on decoding

packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
The spread operator (and Array.assign) loads the entire source array onto the stack, then pushes it onto the destination array. It causes stack overflow with large vector.
=> fix: don't use spread operator when encoding vec

docs/generated/changelog.html, packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
Fixes incorrect decoding of optional struct fields.
A unit test for this corner case has been added.
=> fix: Correctly decode optional struct fields

packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
At the moment trying to encode large binary data is very inefficient because one has to convert them to Array first before passing to the IDL encode function.
In fact trying to convert 100MB ArrayBuffer to Array will result in OOM in Node.js.
This patch adds a special case to type check and allows directly passing ArrayBuffer (e.g. Uint8Array) to the encode function and solves the problem. 
A test case is added.
=> feat: fast ArrayBuffer encoding

packages/agent/package.json, packages/auth-client/package.json, packages/authentication/package.json, packages/candid/package.json, packages/identity-ledgerhq/package.json, packages/identity/package.json, packages/principal/package.json
Signed-off-by: Dominic Woerner <dominic.woerner@dfinity.org>
Homepage link in npm registry was broken and link to repository/package and issue tracking was missing.
=> fix: homepage/repository in package.json

packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/types.ts
Adds the `setBigUint64` polyfill because of the multiple [error reports](https://dfinity.slack.com/archives/C01S03NBM7S/p1654161676609929). (based on [nns-dapp solution](https://github.com/dfinity/nns-dapp/blob/55a89a9b5d5d4241277822197efc62f3d3e8d6ce/frontend/ts/src/canisters/converter.ts#L25))
=> fix: add setBigUint64 polyfill

packages/candid/src/candid-ui.ts, packages/candid/src/idl.ts
Candid UI cannot encode nat8, nat16 types, because the parser only return BigInt for number types.
User get the error: "Cannot convert a BigInt value to a number"
=> fix: Candid UI cannot encode nat8

docs/generated/changelog.html, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
Agent-js should allow to pass on a derivation_origin during login that should be used for principal derivation (as opposed to the front-end origin)
Unit test added
=> feat: adds support for derivationOrigin

docs/generated/changelog.html, e2e/node/basic/basic.test.ts, packages/agent/src/agent/api.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/polling/index.ts
Enable the `readState` of the Agent to reuse the request.
Signing with the hardware wallet requires the user to accept from the device. Reusing the signed request will improve the user experience for hardware wallet users.
I linked a branch of nns-dapp to the changes in this PR and validated that everything worked, not just the new feature.
=> feat: reuse signed request when reading state

docs/generated/changelog.html, packages/agent/tsconfig.json, packages/auth-client/tsconfig.json, packages/authentication/tsconfig.json, packages/candid/tsconfig.json, packages/identity-ledgerhq/tsconfig.json, packages/identity/tsconfig.json, packages/principal/tsconfig.json
After an issue raised with the Create React App experience, we would like to enable enhanced sourcemaps, since we aren't including the source code in our packages
```js
{"version":3,"file":"index.js","sourceRoot":"","sources":["../../../src/agent/index.ts"],"names":[],"mappings":";;;;;;;;;;;;;;;;;AAGA,wCAAsB;AACtB,yCAAuB;AACvB,0CAAwB;AAMxB,SAAgB,eAAe;IAC7B,MAAM,KAAK,GACT,OAAO,MAAM,KAAK,WAAW;QAC3B,CAAC,CAAC,OAAO,MAAM,KAAK,WAAW;YAC7B,CAAC,CAAC,OAAO,IAAI,KAAK,WAAW;gBAC3B,CAAC,CAAC,SAAS;gBACX,CAAC,CAAC,IAAI,CAAC,EAAE,CAAC,KAAK;YACjB,CAAC,CAAC,MAAM,CAAC,EAAE,CAAC,KAAK;QACnB,CAAC,CAAC,MAAM,CAAC,EAAE,CAAC,KAAK,CAAC;IAEtB,IAAI,CAAC,KAAK,EAAE;QACV,MAAM,IAAI,KAAK,CAAC,0BAA0B,CAAC,CAAC;KAC7C;IAED,OAAO,KAAK,CAAC;AACf,CAAC;AAfD,0CAeC"}
```
```js …
```
=> feat: enables inline sourcemaps for packages for developer experience

docs/generated/changelog.html, e2e/node/basic/canisterStatus.test.ts, e2e/node/basic/counter.test.ts, e2e/node/test-setup.ts, packages/agent/src/canisterStatus/index.ts
Previously the utility suppressed the error and returned a map with all fields as null. Now, if you are on the local replica or a testnet, rootkey errors will cause canisterstatus to throw
Fixes SDK-577
new e2e suite for canisterstatus
=> fix: canisterStatus throws if root key is not fetched

docs/generated/changelog.html, packages/agent/README.md, packages/auth-client/README.md, packages/authentication/README.md, packages/candid/README.md, packages/identity/README.md, packages/principal/README.md
There's a nicer format for canister urls with icns. The docs can now avoid a redirect using https://agent-js.icp.xyz
=> chore: replaces links with icp.host to xyz for nice url for docs

docs/generated/changelog.html, package-lock.json, packages/auth-client/package.json, packages/auth-client/src/db.test.ts, packages/auth-client/src/db.ts, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts, packages/auth-client/src/storage.ts, packages/auth-client/test-setup.ts
AuthClient now uses IndexedDb by default, as localStorage is less secure.
Also offers a generic Indexed Db keyval store, IdbKeyVal
I decided to leave out encryption for this PR to reduce overhead - could be added at a later date https://gist.github.com/krpeacock/9203f1c6bbd8c55f2eef5e001223edf2
Fixes SDK-313
Unit test coverage
=> feat: auth-client stores identities in indexeddb

docs/generated/changelog.html, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
This change makes the upgrade to IDB smoother, by checking to see if the user has a delegation stored in localstorage during initialization, if none is found in the default or provided storage implementation. 
unit testing
=> fix: graceful upgrade from localstorage to idb without breaking sessions

packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
To migrate from localstorage to idb, AuthClient tries to find current values in the storage with the incorrect keys - i.e it tries to load `icdelegation` and `icidentity` instead of `ic-delegation` and `ic-identity` and therefore, no session are found and migrated.
This is because a `LocalStorage` object is initialized with the prefix `ic` instead of `ic-`.
I tried to bump agent-js from v0.12.0 v0.13.0 in my project [cycles.watch](https://cycles.watch/) locally and noticed that I lost my session. Then debugged and found the prefix mismatch.
This PR is a follow-up to PR #606 and release of agent-js v0.13.0 ([changelog](https://github.com/dfinity/agent-js/releases/tag/v0.13.0))
All consumers used to inherits prefix `ic-` or was it an option? If it was a variable that can be set by the …
=> fix: migration from localstorage to idb

demos/ledgerhq/package.json, demos/sample-javascript/package.json, docs/generated/changelog.html, e2e/browser/package.json, e2e/node/package.json, package-lock.json, package.json, packages/agent/package.json, packages/auth-client/package.json, packages/authentication/package.json, packages/candid/package.json, packages/identity-ledgerhq/package.json, packages/identity/package.json, packages/principal/package.json
fixes a bug with the migration from localstorage
=> chore: release v0.13.1

packages/auth-client/src/db.ts, packages/auth-client/src/index.ts, packages/auth-client/src/storage.ts
`auth-client` cannot be used in web worker or in NodeJS context  because `window.localStorage` is not available.
e.g. stacktrace while trying to use `v0.13.1` in a jest test:
> ReferenceError: localStorage is not defined
> 
>       18 |  */
>       19 | export const createAuthClient = (): Promise<AuthClient> =>
>     > 20 |   AuthClient.create({
>          |              ^
>       21 |     idleOptions: {
>       22 |       disableIdle: true,
>       23 |       disableDefaultIdleCallback: true,
> 
>       at _openDbStore (node_modules/@dfinity/auth-client/src/db.ts:15:3)
>       at Function.create (node_modules/@dfinity/auth-client/src/db.ts:74:22)
>       at node_modules/@dfinity/auth-client/src/storage.ts:74:17
>       at IdbStorage.get _db [as _db] …
=> fix: auth-client usage in web worker and nodejs

packages/auth-client/src/index.ts
The `logout` function does not `await` for the storage to be cleared before reloading the window. This can lead to an edge case race condition where the storage would partially cleared after logout while the window is reloaded.
NNS-dapp PR [#1247](https://github.com/dfinity/nns-dapp/pull/1247)
Jest test in nns-dapp that failed:
```
it("agent-js should clear indexeddb auth info on logout", async () => {
const idbStorage = new IdbStorage();
await idbStorage.set("delegation", "value");
const value = await idbStorage.get("delegation");
expect(value).not.toBeNull();
await logout({});
const valueCleared = await idbStorage.get("delegation");
expect(valueCleared).toBeNull(); // <--- value was still set
});
```
=> fix: logout clear storage missing promise await

docs/generated/changelog.html, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
Auth Client moves key fallback generation to the create method instead of login and makes the _key non-nullable. This fixes a regression with async window.open behavior in Safari
Fixes #619
=> fix: resolves window.open issue in safari due to async storage call

dfx.json, docs/generated/changelog.html, e2e/node/basic/canisterStatus.test.ts, packages/agent/src/actor.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.ts, packages/agent/src/polling/index.ts
In order to accommodate environments where web assembly is not supported, allows a polyfill for BLS verification to be passed during the creation of an Actor. Unblocks React Native support
=> feat: support for bls verification polyfill

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts
fixes some flaky tests for the synctime feature
=> fix: time tests only use faketimers once

docs/generated/changelog.html, packages/candid/src/idl.ts
https://forum.dfinity.org/t/agentjs-candid-pinpointed-type-errors-upgrade-pr/15685
=> feat: AgentJs Candid Pinpointed Type Errors upgrade - PR

.gitignore, docs/generated/changelog.html, package-lock.json, packages/principal/package.json
Principal was using a package used elsewhere but was not included in its package dependencies
Fixes #522
=> chore: adds js-sha256 dependency to principal

docs/generated/changelog.html, package-lock.json, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts, packages/bls-verify/tsconfig.json, packages/bls-verify/types/amcl.d.ts
I observed by setting a low timeout that idlemanager was firing even when I had not logged in. This changes the logic so that the idle timeout does not start counting unless an identity is passed in `idleOptions`, or after `authClient.login` succeeds.
New unit tests
=> fix: idlemanager starting before login suceeds

.github/workflows/size-limit.yml, package.json
=> test: enabling comparison job

docs/generated/changelog.html, packages/auth-client/src/__snapshots__/index.test.ts.snap, packages/auth-client/src/db.test.ts, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts, packages/auth-client/src/storage.ts
Now that we have the non-exportable ECDSAKeyIdentity using CryptoKeys, we can use it as the base key for II Delegations. 
Fixes # FOLLOW-814
New unit tests, also by compiling the package and using it in the auth-client-demo application
[FOLLOW-814]: https://dfinity.atlassian.net/browse/FOLLOW-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: migrate to secure ECDSA key for auth-client

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/agent/http/transforms.ts
During the SNS-1 launch retrospective, we identified the difficulty in identifying retried requests as a pain point. 
Adding a unique request id header (using the standard key, despite the similarity to the Request ID specified for checking the status of updates in the Internet Computer Specification
Fixes # SDK-880
new unit tests
=> feat: introduces X-Request-ID header to more easily identify retried requests

docs/generated/changelog.html, packages/agent/src/canisterStatus/index.ts
chore: removes a circular dependency on index for canisterStatus
=> chore: removes a circular dependency on index for canisterStatus

.github/workflows/lint.yml, .github/workflows/prettier.yml, docs/generated/changelog.html, e2e/browser/package-lock.json, packages/agent/README.md, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
Lists icp-api.io as the default host in documentation. Also
- adds rewrite support for subdomains the same way as ic0.app
- for icp-api.io
- for icp0.io
New unit tests
=> feat: changes default host and supports icp-api.io

docs/generated/changelog.html, packages/identity/src/identity/webauthn.ts
This PR extends the WebAuthnIdentity with [authenticatorAttachment](https://w3c.github.io/webauthn/#dom-publickeycredential-authenticatorattachment). In addition, the constructor is made public to allow downstream projects to construct it more easily.
This is required for Internet Identity to record the authenticatorAttachment on devices being registered.
There are no tests for `WebAuthnIdentity`. However, similar code has been tested in [II code](https://github.com/dfinity/internet-identity/blob/main/src/frontend/src/utils/multiWebAuthnIdentity.ts#L118).
=> feat: Extend WebAuthnIdentity with AuthenticatorAttachment

docs/generated/changelog.html, package-lock.json, package.json, packages/candid-ui/.gitignore, packages/candid-ui/README.md, packages/candid-ui/candid-core.ts, packages/candid-ui/candid-ui.ts, packages/candid-ui/index.ts, packages/candid-ui/package.json, packages/candid-ui/tsconfig-cjs.json, packages/candid-ui/tsconfig.json, packages/candid/src/index.ts, packages/candid/tsconfig.json
Since `@dfinity/candid` is a dependency for all packages, many applications do not require the Candid UI contents. Splitting it out will also give us the ability to further contribute to Candid UI independently.
`@dfinity/candid-ui` will ship as a ESM library to make it easier to include in websites
Testing to come
=> feat: separates candid-ui into its own package

docs/generated/changelog.html, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts
The `onSuccess` callback was called before writing the delegation chain to storage. Since the writing of the chain to storage is asynchronous, an app that performs some full page navigation or a page refresh in their `onSuccess` callback _might_ interrupt the operation.
This was causing flakiness in some e2e tests that I was working on for a dapp. Roughly 20% of the runs were failing. Making this change removes the flakiness and the tests pass now 100% of the time.
=> fix: finish all tasks before calling onSuccess callback

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/agent/http/transforms.ts
Due to the use of Headers inside of Agent-JS, it introduced a nodejs compatibility issue. We can simply swap back with no impact on the functionality
Fixes #685 
Unit tests
=> fix: reverts use of Headers for improved node compatibility

docs/generated/changelog.html, packages/identity/src/identity/webauthn.ts
Fix typo in `JsonnableWebAuthnIdentitiy`, breaking change that requires users to update their imports to `JsonnableWebAuthnIdentity` when this type is used.
=> fix: Typo in JsonnableWebAuthnIdentitiy

docs/generated/changelog.html, packages/candid/src/idl.test.ts, packages/candid/src/idl.ts
This change adds a new query type: `composite_query` in idl.ts.
It corresponds to the following changes in the upstream candid:
- https://github.com/dfinity/candid/pull/420 (spec change)
- https://github.com/dfinity/candid/pull/435 (rust change)
=> feat: support composite_query in candid

docs/generated/changelog.html, packages/agent/src/actor.test.ts, packages/agent/src/actor.ts, packages/agent/src/agent/api.ts, packages/agent/src/agent/http/__snapshots__/http.test.ts.snap, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
Handles the new update call error messages introduced in [IC-1462](https://github.com/dfinity/interface-spec/pull/143). 
Corresponds to https://github.com/dfinity/agent-rs/pull/422. 
This PR includes a unit test for the new update call behavior. 
I also ran a local sanity check using the setup described in [this forum post](https://forum.dfinity.org/t/not-calling-accept-message-in-inspect-message-not-rejecting-immediately-in-dfx-0-14-2-beta-2/21105), replacing Candid UI with a simple webapp pointing to a local `agent-js` installation. 
[IC-1462]: https://dfinity.atlassian.net/browse/IC-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: handle new update call errors (IC-1462)

demos/sample-javascript/package.json, e2e/browser/package.json, e2e/node/package.json, package-lock.json, package.json, packages/agent/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/bls-verify/package.json, packages/candid/package.json, packages/identity-secp256k1/package.json, packages/identity/package.json, packages/principal/package.json
Release agent-js 0.17.0 to incorporate a [bug fix](https://github.com/dfinity/agent-js/pull/734) and [support for the new `composite_query` keyword](https://github.com/dfinity/agent-js/pull/730).
=> chore: release v0.17.0

docs/generated/changelog.html, packages/agent/README.md, packages/agent/src/actor.test.ts, packages/agent/src/actor.ts, packages/agent/src/agent/api.ts, packages/agent/src/agent/http/__snapshots__/http.test.ts.snap, packages/agent/src/agent/http/errors.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/agent/http/transforms.ts, packages/agent/src/agent/http/types.ts, packages/agent/src/agent/proxy.ts
This PR extens the `query` and `call` method responses to include the boundary node http headers. Moreover, it introduces a new method to the actor creation that enriches the provide type to include the http details of call.
- http calls responses are tested with snapshots
- `requestAndRetry` logic is validated by using a custom error type `AgentHTTPResponseError `
- actor interface is tested by mocking the pollForResponse and testing that both `createActor` and `createActorWithHttpDetails` return the same decoded response and that the later also includes the expected `httpDetails`
- Linked locally with the service worker and manually validated the integration
=> feat: expose boundary node http headers to calls

demos/sample-javascript/package.json, e2e/browser/package.json, e2e/node/package.json, package-lock.json, package.json, packages/agent/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/bls-verify/package.json, packages/candid/package.json, packages/identity-secp256k1/package.json, packages/identity/package.json, packages/principal/package.json
Release to include https://github.com/dfinity/agent-js/pull/736 - exposing boundary node http headers.
=> chore: release v0.18.0

docs/generated/changelog.html, packages/agent/src/actor.ts
We cannot call composite query from agent-js at the moment, because it's been categorized as update call.
=> fix: fix composite query support in actor.ts

docs/generated/changelog.html, packages/agent/src/agent/http/index.ts
To ease the pain of development, sets a default host of https://icp-api.io for HttpAgent if none can be inferred, and none is provided.
Logs a warning encouraging the developer to set a host in the HttpAgent options
=> feat: HttpAgent now uses a default address

docs/generated/changelog.html, package-lock.json, packages/agent/package.json, packages/agent/src/request_id.ts, packages/agent/src/utils/buffer.ts, packages/assets/package.json, packages/assets/src/index.ts, packages/identity-secp256k1/package.json, packages/identity-secp256k1/src/secp256k1.test.ts, packages/identity-secp256k1/src/secp256k1.ts, packages/identity/package.json, packages/identity/src/identity/ecdsa.test.ts, packages/principal/package.json, packages/principal/src/utils/sha224.ts
Due to an ongoing incident where the js-sha256 library is breaking on new versions of Chrome, we are replacing it with the industry standard library, @noble/hashes
This is a compact, audited, pure JS library, and it is able to produce hashes synchronously, which makes it easier to drop into our library than the WebCrypto.subtle.digest api, which is promise-based.
Updates to a few unit tests, and running against existing golden canonical hashes and e2e test suite
=> feat: replaces the `js-sha256` library with `@noble/hashes`

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
The previous release adding a default host was not working as intended. This fixes the logic and makes it more robust
=> fix: default host logic fixed and tests added

docs/generated/changelog.html, packages/agent/src/actor.test.ts, packages/agent/src/actor.ts
As a common error, many users report getting `Impossible to convert undefined to Principal` without knowing what they need to do. This PR adds a more helpful error at the point of Actor creation, providing a more helpful suggestion for newer developers. For example: https://discord.com/channels/748416164832608337/748416164832608341/1145754858448756766
=> feat: enhanced error message for missing canister id

.github/workflows/e2e-tests.yml, .github/workflows/lint.yml, .github/workflows/mitm.yml, .github/workflows/prettier.yml, .github/workflows/size-limit.yml, .github/workflows/unit-tests.yml, docs/generated/changelog.html
CI started failing after running `npm i -g npm` because version 10 is not compatible with node 16
=> chore: lock npm version for CI

docs/generated/changelog.html, packages/agent/src/canisterStatus/index.test.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.test.ts, packages/agent/src/certificate.ts, packages/agent/src/utils/leb.ts, packages/bls-verify/src/index.test.ts
The time on certificates returned by [read_state](https://internetcomputer.org/docs/current/references/ic-interface-spec/#http-read-state) requests is currently not checked in agent-js.
It is a good practice to check the time to avoid using stale data. For example, we do it for asset certification in the service worker because otherwise a malicious node could serve stale/outdated HTTP assets. 
Fixes SDK-1132
new unit tests with mocked time and custom errors
=> feat: certificate time checks

docs/generated/changelog.html, packages/agent/src/canisterStatus/__snapshots__/index.test.ts.snap, packages/principal/src/index.test.ts, packages/principal/src/index.ts
`JSON.stringify(principal)` currently uses `Uint8Array` encoding instead of `toString`. Adding the `toJSON` method resolves this
new unit tests
=> feat: Principal class serializes to JSON

docs/generated/changelog.html, package-lock.json, packages/agent/package.json, packages/agent/src/canisterStatus/__snapshots__/index.test.ts.snap, packages/principal/src/index.test.ts, packages/principal/src/index.ts
@peterpeterparker brought up compatibility with `@dfinity/utils` in #766, and I agreed that we should use that standard for more concrete serialization. Instead of the string, will instead return an object,
```
{"__principal__":"ryjl3-tyaaa-aaaaa-aaaba-cai"}
```
matching a newly exported key, `JSON_KEY_PRINCIPAL`, and a returning a new type, `JsonnablePrincipal`.
Also extends the `fromText` and `from` constructors to support strings using the JSON-serialized principals
=> fix: Principal JSON is compatible with @dfinity/utils jsonReviver helper

packages/identity/src/identity/delegation.ts
Template literal was compiling incorrectly, causing a space to be added in the middle of the BigInt conversion of DelegationChain.fromJson(), causing a throw on AuthClient.create(), causing _deleteStorage() to be called, preventing some users from remaining authenticated to call anything after connecting.
...
Users not being able to make calls after an otherwise successful connect.
Chrome v116, manual e2e testing found the error on connecting to stoic wallet with affected version of Chrome, the pathway of the throw explains the condition users not being able to make calls, unverified if it solves the problem but it looks like it should. Chrome v117 (beta) does not have this issue on most devices.
=> fix: bigint toJson trailing space

docs/generated/changelog.html, package.json
increases size limit for agent-js to allow for Ed25519 support for node key signature verification
=> chore: increases size limit for agent-js

docs/generated/changelog.html, packages/agent/src/utils/expirableMap.test.ts, packages/agent/src/utils/expirableMap.ts
For the sake of FOLLOW-1302, but also as a general utility, we can provide a class that implements a standard Map, but includes expiration times for all its entries. It will return undefined for any value that has gone stale
new unit test coverage
=> feat: introduces ExpirableMap

docs/generated/changelog.html, e2e/node/basic/mainnet.test.ts, packages/agent/src/canisterStatus/__snapshots__/index.test.ts.snap, packages/agent/src/canisterStatus/index.ts
We had a bug noted where not all controllers were being reported. This fixes the issue and adds tests against mainnet
=> fix: canisterStatus returns full list of controllers

.github/workflows/e2e-tests.yml, demos/sample-javascript/package.json, e2e/browser/cypress.config.js, e2e/browser/cypress/e2e/ecdsa.cy.js, e2e/browser/package.json, e2e/node/basic/assets.test.ts, e2e/node/basic/basic.test.ts, e2e/node/basic/identity.test.ts, e2e/node/basic/mainnet.test.ts, e2e/node/basic/mitm.test.ts, e2e/node/canisters/counter.ts, e2e/node/canisters/declarations/counter/counter.did.d.ts, e2e/node/canisters/declarations/counter/counter.did.js, e2e/node/package.json, e2e/node/test-setup.ts, package-lock.json, package.json, packages/agent/package.json, packages/agent/test-setup.ts, packages/assets/package.json, packages/auth-client/package.json, packages/bls-verify/package.json, packages/candid/package.json, packages/identity-secp256k1/package.json, packages/identity/package.json, packages/identity/src/identity/ecdsa.ts, packages/principal/package.json
=> chore: release v0.20.0

docs/generated/changelog.html, e2e/node/basic/mitm.test.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
Because a node can be upgraded while the cache is stale, we should retry a failed query signature verification once, after refreshing the cache
=> feat: retry query signature verification in case cache is stale

docs/generated/changelog.html, packages/auth-client/src/index.ts
Correctly honor `disableIdle` flag for the idle manager.
Fixes # (576)
https://github.com/dfinity/agent-js/issues/576
Do not created the idle manager if `disableIdle` flag is passed on successful login. Tested this via usage in DSCVR.
=> fix: honor disableIdle flag

docs/generated/changelog.html, packages/auth-client/src/index.ts, packages/identity/src/identity/delegation.test.ts, packages/identity/src/identity/delegation.ts, packages/identity/src/identity/partial.test.ts, packages/identity/src/identity/partial.ts
To get a delegation from Internet Identity, the Auth Client allowed the developer to initialize the client using an existing identity. However, since the delegation can target any public key, it can be useful to allow the client to accept a "partial" identity class without a private key.
Introduces the `PartialIdentity` and `PartialDelegationIdentity` classes in `@dfinity/identity`, which can now be passed into `AuthClient.create`
This will be useful to remove the limitations such as adding an intermediary identity, as used by our deep link example: https://github.com/dfinity/examples/blob/c62de1a928fa0bf6b8fdbbbf0e0204e7cf5d6dfb/native-apps/unity_ii_applink/ii_integration_dapp/src/greet_frontend/src/index.js#L49
New Unit tests
=> feat: introduces partial identity

docs/generated/changelog.html, package-lock.json, packages/candid/src/idl.test.ts, packages/candid/src/idl.ts, packages/candid/src/utils/buffer.ts, packages/candid/src/utils/hash.ts, packages/candid/src/utils/leb128.ts
We've had some warnings appearing in the files tab due to not strictly enforcing our linting in CI for issues such as jsdoc conventions. This PR cleans those up.
Also fixes an issue in leb128 where a returned value would be a Uint8Array when it is typed as an ArrayBuffer that I noticed while cleaning up the doc types.
Fixes #811 
Standard suite
=> chore: GitHub actions warning cleanup

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
This PR includes `github.dev` and `gitpod.io` in the list of known `HttpAgent` hosts to support remote IDE development out of the box. The context for this change can be found in the internal `#poc-dev-env-in-5-mins` Slack channel as well as [this forum conversation](https://forum.dfinity.org/t/issue-with-candid-ui-and-online-ide-gitpod-codespaces/26148).
CC @chenyan-dfinity
=> feat: add `github.dev` and `gitpod.io` to known hosts

docs/generated/changelog.html, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
Follow-up for [this forum conversation](https://forum.dfinity.org/t/agent-js-0-21-2/26900/2) with improved test coverage.
=> fix: distinguish remote dev environments from known hosts

.github/workflows/publish.yml, bin/version.ts, docs/generated/changelog.html, package.json
* runs prettier on json files before writing during release PR
* creates a checkbox that hopefully will trigger CI in the automated release PR
* adds the `-ws` flag to `npm publish`
=> feat: release automation changes

docs/generated/changelog.html, packages/agent/src/agent/index.ts
`AgentHTTPResponseError` is not exported from the agent library. It would be nice if it was.
Not tested.
=> feat: Export AgentHTTPResponseError

docs/generated/changelog.html, e2e/node/basic/mainnet.test.ts
Updates snapshot to reflect newly added controller for cycle monitoring
=> chore: adding new controller to mainnet test snapshots

docs/generated/changelog.html, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.ts
feat: new CustomPath class, better docs, and deprecating metadata path type for CanisterStatus
=> feat: customPath changes

docs/generated/changelog.html, e2e/node/basic/basic.test.ts, packages/agent/src/actor.ts, packages/agent/src/canisters/management_idl.ts, packages/agent/src/canisters/management_service.ts
brings in new features into the management canister interface, generated through didc. Includes breaking changes to the interface
Fixes # SDK-1352
N/A
=> chore: update management canister interface

docs/generated/changelog.html, packages/auth-client/src/index.ts
By exporting the `AuthClientStorage` interface, users can easily create custom implementations of it.
It doesn't need to be tested given that all it does is export a type which was previously private.
=> chore: export `AuthClientStorage` to aid with custom implementations

docs/generated/changelog.html, package-lock.json, packages/identity/src/identity/ed25519.test.ts, packages/identity/src/identity/ed25519.ts
A bug was discovered where the Ed25519KeyIdentity was generating an insecure, repeatable identity. This patches the issue and adds new testing to ensure the generate method yields fresh identities when no seed is passed.
Fixes FOLLOW-1384
added new unit tests
=> fix: ed25519KeyIdentity generates unique identities when no seed is provided

docs/CHANGELOG.md, packages/identity/src/identity/webauthn.ts
This PR removes `instanceof ArrayBuffer` checks from the `WebAuthnIdentity`. The reason is that these checks hide errors and cause problem in conjunction with the BitWarden password manager (which sets these fields to `Uint8Array`). See also this issue: https://github.com/dfinity/internet-identity/issues/2235
Simply removing the checks solved the issue entirely, as the fields that supposedly need to be `ArrayBuffer` are converted to `Uint8Array` anyway.
This change was manually tested with Internet Identity and the BitWarden extension in Chrome.
=> fix: Remove ArrayBuffer checks from WebAuthnIdentity

docs/CHANGELOG.md, packages/identity/src/identity/webauthn.ts
This PR fixes an issue that arises from assuming that the `PublicKeyCredential` returned from `navigators.credentials.create` is enumerable.
Manual testing.
=> fix: Work around credentials not being enumerable

bin/roll-changelog.ts, docs/CHANGELOG.md, package-lock.json
pads date numbers in changelog automation. E.G. 2024-3-1 -> 2024-03-01
Manually ran script
=> fix: pads date numbers in changelog automation

docs/CHANGELOG.md, packages/auth-client/src/index.ts
Adds new security features from the II login flow for restricting authentication types: https://github.com/dfinity/internet-identity/blob/6c345912457ca93bf3175ce3382a1ddf8ff46eca/docs/ii-spec.md#client-authentication-protocol
New Login method allows developers to restrict users from authenticating using a PIN
Also allows `onSuccess` to pass through the message from the IDP provider, allowing developers to access the new `authnMethod` field
Tested manually after building and installing in https://github.com/krpeacock/auth-client-demo
=> feat: support for restricting II auth methods

docs/CHANGELOG.md, packages/auth-client/src/storage.ts
`IdbStorage` is a fairly lightweight wrapper around `IdbKeyVal`. `IdbKeyVal` exposes generic `get` and `set` methods whereas `IdbStorage` can only `get` and `set` strings. This seems like an unnecessary restriction and means developers must come up with hacky solutions to work with types other than strings, eg. `CryptoKeyPair`.
I have tested this with a local deployment of OpenChat where it has successfully stored and retrieved values of type string and CryptoKeyPair.
=> feat: make `IdbStorage` `get/set` methods generic

docs/CHANGELOG.md, packages/agent/src/cbor.ts
We have the issue in Internet Identity that people complain about hard to diagnose issues. In particular, we regularly encounter users faced with the "failed to parse" message thrown out of `borc`. It would be very helpful to know what the input was that caused that error.
Against existing test suite.
=> chore: Add context to errors thrown on cbor decode

.github/workflows/size-limit.yml, docs/CHANGELOG.md
replaces globle npm install with setup-node because of a [bug](https://github.com/actions/runner-images/issues/9644) that started happening recently
=> chore: replaces global npm install with setup-node

.github/workflows/conventional-commits.yml, docs/CHANGELOG.md
Same issue as last time - CI is broken
Fixes SDK-1669
Tested on a personal repo: https://github.com/krpeacock/server/pull/13
=> chore: updates dfinity/conventional-pr-title-action to v4.0.0

demos/sample-javascript/src/index.html
The URLs used in the sample are outdated and do not work anymore. I replaced them with the current URLs. However, I couldn't fix the canister ID as I am not sure what canister it should be.
I updated it and ran it manually. Of course I got an error because the canister doesn't exist anymore, but at least it went through a boundary node and hit a replica.
=> fix: updated outdated urls in sample

docs/CHANGELOG.md, e2e/node/basic/basic.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.test.ts, packages/agent/src/certificate.ts, packages/agent/src/polling/index.ts, packages/assets/src/index.ts
Adds support for proof of absence in certificate lookups. Previously a lookup with either return a value or `undefined` if the value cannot be found. Now the result of a lookup will differentiate between `Found`, `Unknown` and `Absent`, which allows clients to tell the difference between a value that is provably absent from the tree, or one that _might_ have been pruned from the tree (maliciously or otherwise).
Fixes # [SDK-1219](https://dfinity.atlassian.net/browse/SDK-1219)
I've added new unit tests to cover the new lookup functionality.
[SDK-1219]: https://dfinity.atlassian.net/browse/SDK-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add support for proof of absence in certificate lookups

docs/CHANGELOG.md, packages/agent/src/agent/http/index.ts, packages/agent/src/observable.test.ts, packages/agent/src/observable.ts
Funded app reported that in Chrome browser extensions, the Function / Proxy implementation was being rejected under rules blocking the use of `eval`. 
Once Funded has tested the changes in their extension, this can be merged
=> fix: ObservableLog no longer extends Function

bin/update-management-idl.ts, docs/CHANGELOG.md, e2e/node/basic/mainnet.test.ts, e2e/node/canisters/declarations/counter/counter.did, package-lock.json, package.json, packages/agent/src/actor.ts, packages/agent/src/agent/http/__snapshots__/http.test.ts.snap, packages/agent/src/agent/http/http.test.ts, packages/agent/src/canisters/management.did, packages/agent/src/canisters/management_idl.ts, packages/agent/src/canisters/management_service.ts
As requested, removes the bitcoin query methods from the management canister IDL
=> feat: strips out bitcoin query methods from management canister IDL

.github/workflows/e2e-tests.yml, docs/CHANGELOG.md, e2e/node/basic/mainnet.test.ts
Fixes an issue where Cypress CI stopped working for e2e tests by using the cypress github action
=> ci: npm cache and cypress action

.github/workflows/e2e-browser-tests.yml, .github/workflows/e2e-tests.yml, docs/CHANGELOG.md, e2e/browser/cypress/e2e/ecdsa.cy.js, e2e/node/basic/mainnet.test.ts
Continuing to troubleshoot issues with cypress tests. This breaks out node and e2e tests and gets the CI back to green
=> ci: fix cypress

.github/workflows/prepare-release.yml, docs/CHANGELOG.md
Releases are broken. See https://github.com/dfinity/agent-js/actions/runs/9946592301/job/27477470996
=> ci: changing github token for creating release

docs/CHANGELOG.md, packages/identity-secp256k1/src/secp256k1.test.ts, packages/identity-secp256k1/src/secp256k1.ts
Throws an error if the seed returned by `mnemonicToSeedSync` is not 64 bytes long.
I could not find an example seed that produces the behavior, but added tests that ensure that invalid mnemonics are handled correctly
New unit tests
=> feat: ensure that seed phrase must produce a 64 byte seed

docs/CHANGELOG.md, e2e/node/basic/mainnet.test.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
In order to support Utopia or other non-mainnet replicas with known root keys, allows rootKey to be passed during HttpAgent creation
new e2e test
=> feat: new option for setting rootKey during agent creation

docs/CHANGELOG.md, packages/agent/src/agent/api.ts
Improves some vague language and adds a link to documentation about the use of effectiveCanisterId
=> docs: clarifies meaning of `effectiveCanisterId` in `CallOptions`

docs/CHANGELOG.md, packages/agent/src/certificate.ts, packages/agent/src/index.ts, packages/agent/src/polling/index.ts
Noted by @peterpeterparker - the agent doesn't export the utilities out of the polling submodule.
At the same time, I've set the default polling strategy as an actual default, and the argument can now be omitted
=> feat: exports polling utilities from `@dfinity/agent`

docs/CHANGELOG.md, package-lock.json, packages/use-auth-client/README.md, packages/use-auth-client/examples/auth-demo/deps/candid/ivcos-eqaaa-aaaab-qablq-cai.did, packages/use-auth-client/examples/auth-demo/deps/init.json, packages/use-auth-client/examples/auth-demo/deps/pulled.json, packages/use-auth-client/examples/auth-demo/dfx.json, packages/use-auth-client/examples/auth-demo/src/auth-demo-frontend/src/App.tsx, packages/use-auth-client/examples/auth-demo/src/auth-demo-frontend/tsconfig.json, packages/use-auth-client/src/use-auth-client.ts, packages/use-auth-client/test/use-auth-client.test.tsx
As requested, allows the `useAuthClient` hook to create and manage multiple actors at once. I don't know how to infer the full typing, but that may be possible in a future version
Also adds example code for initializing multiple actors
new unit test and refactoring in the example app
=> feat: multi-actor config

docs/CHANGELOG.md, packages/agent/src/certificate.ts
Exposes the raw certificate from the `Certificate` class as `Certificate.cert`. 
Partially fixes SDK-1828
=> feat: expose inner certificate in Certificate

packages/use-auth-client/tsconfig.json
It's impossible to use `@dfinity/use-auth-client` right now because it points to a non-existing path, the package.json points to `lib/(esm|cjs)/index.js`
=> fix: build paths on use-auth-client

packages/assets/src/canisters/assets_idl.js, packages/assets/src/canisters/assets_service.ts, packages/assets/src/index.ts
Allow to pass in headers when storing asset
Fixes #924 
Type check
=> feat(asset): add headers to StoreArgs

packages/agent/src/actor.ts
`recieve` -> `receive`.
This is spotted during our adoption of *agent_dart*.
=> chore: Correct the typo in `agent/src/actor.ts`

docs/CHANGELOG.md, packages/auth-client/src/index.ts
Removes a warning that users found unhelpful, when a message originates from other sources than the identity provider in `AuthClient` during authentication.
=> chore: removes message warning in auth-client

README.md
Update the document about how to run the tests.
Only document change.
=> chore: update the document.

docs/CHANGELOG.md, package-lock.json, packages/agent/src/actor.ts, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.test.ts
Since the root key cannot be fetched inside a synchronous constructor, we should await the root key when the `shouldFetchRootKey` flag is set.
This PR adds a guard to the `HttpAgent` async calls to make sure the root key call has finished before making the call. It also modifies some checks for `rootKey` in the `canisterStatus` and `actor` utils that should instead wait for the call to be completed.
This shores up occasional inconsistencies with the agent during local development, and that have affected projects in our examples repostory
Fixes # SDK-1905
New tests added to the HttpAgent unit test suite
=> feat: fetch root key before making calls

docs/CHANGELOG.md, e2e/node/basic/mainnet.test.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/certificate.ts
which can allow readState calls to work beyond 5 minutes
Because we’ve added to the specification a feature that the check of the ingress_expiry is [skipped](https://github.com/dfinity/ic/pull/1768) for anonymous read_state requests (see [spec](https://github.com/dfinity/interface-spec/pull/343)), we can add this logic to the agent.
Fixes SDK-1953
New e2e test against mainnet
=> feat: HttpAgent uses anonymous identity to make syncTime call

demos/sample-javascript/package.json, docs/CHANGELOG.md, e2e/node/basic/canisterStatus.test.ts, e2e/node/package.json, package-lock.json, package.json, packages/agent/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/candid/package.json, packages/identity/package.json, packages/principal/package.json, packages/use-auth-client/package.json
I just wanted a simple reference for how to do this, and the additional test coverage doesn't hurt
=> test: added e2e test for CanisterStatus subnet path

docs/CHANGELOG.md, packages/agent/src/agent/http/http.test.ts, packages/agent/src/agent/http/index.ts
Allows httpagent.call to be provided with a nonce, overriding all transforms. Also is more resilient to ArrayBuffer vs Uint8Array
unit test added
=> feat: allows httpagent.call to be provided with a nonce

demos/sample-javascript/src/index.html, docs/CHANGELOG.md, package-lock.json, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts, packages/use-auth-client/README.md, packages/use-auth-client/examples/auth-demo/src/auth-demo-frontend/src/App.tsx
Change the identity provider default URL to `https://identity.internetcomputer.org`.
=> feat: Change auth-client's default identity provider url

docs/CHANGELOG.md, packages/identity/src/identity/delegation.test.ts, packages/identity/src/identity/delegation.ts, packages/identity/src/identity/ed25519.test.ts, packages/identity/src/identity/ed25519.ts, packages/identity/src/identity/partial.ts
The msg and signature arguments were being passed into @noble/curves in the incorrect sequence
Fixes #943 
closes SDK-2073
Fixes existing unit test
=> fix: fixes a bug in the Ed25519KeyIdentity verify implementation

docs/CHANGELOG.md, e2e/node/basic/basic.test.ts, e2e/node/canisters/counter.ts
Our e2e changes started failing with the release of dfx 0.26.0 and calls to the management canister. Now we use a dynamic default effective canister id for when there are no known canisters on the entire network in the tests
=> test: fixes e2e tests for compatibility with dfx 0.26.0

docs/CHANGELOG.md, packages/agent/src/agent/http/index.ts, packages/identity/src/identity/ed25519.ts
where the output was not an arraybuffer
Fixes #989
Closes SDK-2078
=> fix: fixes a bug in Ed25519KeyIdentity `toRaw`

.github/workflows/unit-tests.yml
the pinned version of ubuntu just was deprecated: https://github.com/actions/runner-images/issues/11101
using ubuntu latest going forward
=> ci: ubuntu latest for unit tests

e2e/node/basic/mitm.test.ts, packages/agent/src/actor.ts, packages/agent/src/canisterStatus/index.ts, packages/agent/src/cbor.ts, packages/agent/src/certificate.test.ts, packages/agent/src/certificate.ts, packages/agent/src/der.ts, packages/agent/src/errors.ts, packages/agent/src/index.ts, packages/agent/src/polling/index.ts, packages/agent/src/polling/strategy.ts, packages/agent/src/public_key.ts, packages/agent/src/request_id.ts, packages/agent/src/utils/buffer.ts
Refactor the error system in the `@dfinity/agent` package to reflect Rust agent's implementation.
For now, I've added the error types and replaced all the internal `throw` statements with the new error system. This PR shouldn't break anything. In a follow-up PR, I'll refactor the agent and the actor errors in order to use the new error system across all the `@dfinity/agent` package.
Updated tests and assertions where already present.
=> refactor: use new error system and error codes

packages/agent/src/actor.ts, packages/agent/src/agent/http/index.ts, packages/agent/src/auth.ts, packages/agent/src/certificate.ts, packages/agent/src/constants.ts, packages/agent/src/index.ts, packages/agent/src/request_id.ts, packages/agent/src/utils/buffer.ts, packages/candid/src/utils/buffer.ts, packages/identity-secp256k1/src/secp256k1.ts, packages/identity/src/identity/delegation.ts, packages/identity/src/identity/ed25519.test.ts, packages/identity/src/identity/ed25519.ts
- Removes unnecessary `uint8FromBufLike` calls
- Moves the domain separators to the constants in the agent
Same tests as before
=> refactor: remove unnecessary `uint8FromBufLike` calls

.github/actions/prepare/action.yml, .github/workflows/e2e-tests.yml, .github/workflows/lint.yml, .github/workflows/mitm.yml, .github/workflows/npm-audit.yml, .github/workflows/prepare-release.yml, .github/workflows/prettier.yml, .github/workflows/publish.yml, .github/workflows/size-limit.yml, .github/workflows/unit-tests.yml, package-lock.json, package.json
Add a shared action to prepare the node environment.
Additionally, it bumps the major version of `release-it` from v18 to v19. No breaking changes according to [their changelog](https://github.com/release-it/release-it/blob/main/CHANGELOG.md).
CI passing
=> ci: prepare node action

docs/CHANGELOG.md, packages/agent/src/certificate.ts, packages/agent/src/request_id.test.ts, packages/agent/src/request_id.ts
Removes the `hash` exported function.
Same tests should pass
=> feat!: replace `hash` with `sha256` from `@noble/hashes/sha2` to take advantage of existing dependencies

packages/assets/src/index.ts, packages/identity-secp256k1/src/secp256k1.test.ts, packages/identity-secp256k1/src/secp256k1.ts, packages/identity/src/identity/ecdsa.test.ts, packages/principal/src/index.ts, packages/principal/src/utils/sha224.ts
Remove useless utility functions and use `sha256` from `@noble/hashes/sha2` as function.
=> refactor: use `@noble/hashes/sha2` consistently

docs/CHANGELOG.md, packages/agent/src/cbor.ts, packages/agent/src/utils/buffer.ts
Replaces the `concat` exposed function.
Same tests should pass.
=> feat!: replace `concat` with `concatBytes` from `@noble/hashes/utils`

packages/identity-secp256k1/src/secp256k1.test.ts, packages/principal/src/index.ts
Minor changes
Same tests should pass.
=> refactor: use hex utils from `@noble/hashes`

package-lock.json, packages/identity/package.json
I have just updated OpenChat to use v3.0.0-beta.0, but I had to manually add a dependency on `@noble/hashes` because prior to this PR it is only listed as a dev dependency of `@dfinity/identity` even though it is used at run time.
It is not a dev dependency of any other packages in this workspace.
It only moves a dependency from `devDependencies` to `dependencies`, so testing is not required.
=> fix: mark `@noble/hashes` as a dependency rather than a dev dependency

eslint.config.mjs
=> chore: ignore `docs` and `.dfx` folders in eslint

CHANGELOG.md, bin/version.ts, package.json, pnpm-lock.yaml
Noticed this was broken while making the release today. It still doesn't account for a different version between core and other packages. Should we add that support while we're at it? We'll need to update the "prepare release" github action to have two inputs if we want to have multiple versions handled
=> chore: updates the version script to work with new pnpm workspaces

packages/auth-client/package.json, packages/auth-client/src/__snapshots__/index.test.ts.snap, packages/auth-client/src/index.test.ts, packages/auth-client/src/index.ts, packages/auth-client/tsconfig.test.json, packages/use-auth-client/test/use-auth-client.test.tsx, packages/use-auth-client/tsconfig.test.json, pnpm-lock.yaml, tsconfig.json
Updates TS config for `auth-client` and `use-auth-client` to make the IDE load the proper configuration.
Updates the `auth-client` index (and the related test file) to remove unnecessary `await`s.
Updates the `auth-client` index test file to remove deprecated Jest function calls.
Updates the `use-auth-client` test to remove unnecessary `@jest/globals` import.
Updated unit tests should pass.
=> test: update tsconfig, cleanup (auth-client)

packages/agent/.gitignore, packages/agent/lib/esm/package.json, packages/agent/package.json, packages/agent/src/actor.test.ts, packages/assets/.gitignore, packages/assets/lib/esm/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/candid/.gitignore, packages/candid/lib/esm/package.json, packages/candid/package.json, packages/core/.gitignore, packages/core/lib/esm/package.json, packages/core/package.json, packages/identity-secp256k1/.gitignore, packages/identity-secp256k1/lib/esm/package.json, packages/identity-secp256k1/package.json, packages/identity/.gitignore, packages/identity/lib/esm/package.json, packages/identity/package.json, packages/principal/.gitignore, packages/principal/lib/esm/package.json, packages/principal/package.json, packages/use-auth-client/package.json
Changes the order in the `"exports"` fields in the packages' `package.json` file to prioritize ESM modules.
Adds a `package.json` inside each package's `lib/esm` output folder to tell any Node.js app that it's a module. 
=> fix: export ESM modules

README.md
This branch was created to re-trigger the release of 3.0.0, since the previous trigger failed due to the incorrectly configured publish command.
=> docs: remove references to browser e2e tests

.github/workflows/publish.yml
Fixes the steps for publishing docs after the release ot the NPM packages.
I've tested the docs publishing steps locally.
=> ci: fix publish docs steps

docs/src/libs-plugin.ts
Preserve the entities (functions, variables, etc.) names casing in the pages and sidebar titles.
=> docs: preserve entities names casing

docs/scripts/predeploy.sh
Copy `dist/core/404.html` to `dist/404.html` to make Juno's 404 fallback work.
This will be unnecessary once we have a landing page for the root path.
=> docs: copy 404.html to the root to make 404 work

CHANGELOG.md, packages/agent/src/agent/http/index.ts
Use the effective canister id to delete the node keys from the local cache. The fix was already applied in https://github.com/dfinity/agent-js/pull/1081/files#diff-1deee5c6f68eb82e2be634c32d050e818f857292ed0fa9c9e19026e2ef60869cR980-R981, but here we clean the code a bit more and update the changelog.
Additionally, avoids throwing an error in `Promise.all`.
=> fix: use effective canister id to delete the node keys from the local map

CHANGELOG.md, packages/candid/src/idl.ts, packages/candid/src/index.ts
Export generic types from IDL module.
=> fix: export generic types from IDL module

e2e/node/basic/identity.test.ts, packages/core/README.md, packages/core/package.json, packages/core/src/identity-secp256k1/index.ts, packages/core/src/identity/secp256k1/index.ts, packages/core/src/index.ts
Now that we have submodules and tree-shaking, it doesn't make sense to move the secp256k1 package to its own submodule.
=> refactor: move secp256k1 submodule to identity submodule

CHANGELOG.md, packages/candid/src/types.ts
Candid and cbor decoding can return bigints, so we must add that type to the return type.
Fixes https://github.com/demergent-labs/azle/issues/2639.
Same tests should pass.
=> fix: add `bigint` to the `JsonValue` types

packages/agent/README.md, packages/agent/package.json, packages/assets/README.md, packages/assets/package.json, packages/auth-client/README.md, packages/auth-client/package.json, packages/candid/README.md, packages/candid/package.json, packages/identity-secp256k1/README.md, packages/identity-secp256k1/package.json, packages/identity/README.md, packages/identity/package.json, packages/principal/README.md, packages/principal/package.json, packages/use-auth-client/README.md, packages/use-auth-client/package.json
Prepare last patch version of v3.
Only docs changes
=> docs: update links to js.icp.build

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, docs/astro.config.mjs, docs/src/content/docs/upgrading/v3.md, package.json, packages/agent/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/candid/package.json, packages/candid/src/idl.test.ts, packages/core/README.md, packages/core/package.json, packages/identity-secp256k1/package.json, packages/identity/package.json, packages/migrate/package.json, packages/principal/package.json, packages/use-auth-client/package.json
Remove or replace the occurrences of `agent-js` with `icp-js-core`. Once this is merged and the patch version for the packages is released, I will rename the repo on GitHub.
=> chore: rename `agent-js` to `icp-js-core`

CHANGELOG.md, package.json, packages/agent/package.json, packages/assets/package.json, packages/auth-client/package.json, packages/candid/package.json, packages/core/package.json, packages/identity-secp256k1/package.json, packages/identity/package.json, packages/migrate/package.json, packages/principal/package.json
=> chore: release 4.0.1

CHANGELOG.md, packages/agent/src/actor-polling-options.test.ts, packages/agent/src/polling/index.test.ts, packages/agent/src/polling/index.ts, packages/agent/src/polling/strategy.ts
Setting the `defaultStrategy()` on the `DEFAULT_POLLING_OPTIONS` statically results in calling the `timeout` strategy in the chain and starting the timeout. This makes all the read state requests after update calls fail after the configured `FIVE_MINUTES_IN_MSEC`, no matter whether the polling already started or not. This PR fixes the bug by removing the `defaultStrategy()` on the `DEFAULT_POLLING_OPTIONS` and setting it in the `pollForResponse` call.
Ideally, the strategy property in the `pollingOptions` should be a function that returns a `PollStrategy`, but that was unfortunately changed in https://github.com/dfinity/icp-js-core/commit/880f18e11b74fae6a4005622c609c78a709afabe#diff-8e88073ceeb119a7b39f3e6616db4c23f5d3c0e923c194f1f0e5a1a6d54f5835L99. It would require us to make a …
=> fix: create a fresh default polling strategy per request
