dfinity/icp-js-core

packages/agent/src/agent/http/http.test.ts

Increasing unit test coverage
67.03% -> 68.16%

test: httpagent getDefaultFetch test cases

---

.github/workflows/nodejs-ci.yml
package-lock.json
package.json

chore: supports node 16

---

packages/agent/src/certificate.test.ts
packages/agent/src/certificate.ts
packages/agent/src/utils/buffer.test.ts
packages/agent/src/utils/buffer.ts

Also creates some utility methods for working with Uint8Arrays and ArrayBuffers

chore: reducing use of Buffer

---

packages/auth-client/README.md

chore: broken link in auth client readme

---

CONTRIBUTING.md
README.md

chore: adds contribution guidelines

---

packages/auth-client/src/index.ts

Documents the unit for maxTimeToLive and adds a sensible default duration of 1 day

chore: time to live for auth-client

---

packages/agent/src/request_id.test.ts
packages/agent/src/request_id.ts

chore: resolves a bug caused by checking instanceof the Principal class

---

apps/sw-cert/package.json
demos/ledgerhq/package.json
demos/sample-javascript/package.json
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/auth-client/package.json
packages/authentication/package.json
packages/candid/package.json
packages/identity-ledgerhq/package.json
packages/identity/package.json
packages/principal/package.json

I'll do another update with a documentation update based on how this release process goes

chore: releasing 0.10.1 of agent-js

---

packages/agent/src/agent/http/http.test.ts
packages/agent/src/agent/http/index.ts

Rewrite all `*.ic0.app` domains to `ic0.app` to avoid redirects.

feat: add url rewrite to `HttpAgent`

---

docs/generated/changelog.html
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/auth-client/package.json
packages/authentication/package.json
packages/candid/package.json
packages/identity-ledgerhq/package.json
packages/identity/package.json
packages/principal/package.json

Resolves npm warnings issued for typedoc and node-fetch

chore: dependency updates

---

docs/generated/changelog.html

Since we didn't update in #531

chore: updating changelog

---

package-lock.json
package.json
packages/agent/src/utils/buffer.ts
packages/auth-client/src/index.ts
packages/candid/src/candid-core.ts

This blocks publishing the latest docs for 0.10.3

chore: upgrading typescript and typedoc

---

.github/workflows/e2e-tests.yml
.github/workflows/mitm.yml
.github/workflows/nodejs-ci.yml
.github/workflows/unit-tests.yml
README.md
e2e/node/basic/counter.test.ts
e2e/node/basic/identity.test.ts
e2e/node/basic/mitm.test.ts
e2e/node/utils/agent.ts
package-lock.json

also switches from ic-ref to dfx

test: fix mitm and break out tests into different suites

---

lerna.json

[SDK-323] We have migrated off lerna and no longer need this file.
[SDK-323]: https://dfinity.atlassian.net/browse/SDK-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: removes lerna.json

---

demos/ledgerhq/package.json
demos/sample-javascript/package.json
e2e/node/package.json
package.json
packages/agent/package.json
packages/auth-client/package.json
packages/authentication/package.json
packages/candid/package.json
packages/identity-ledgerhq/package.json
packages/identity/package.json
packages/principal/package.json

This is to publish a polyfill for ios<15
There are no code changes in this PR.

chore: release v0.11.3

---

demos/ledgerhq/package.json
demos/sample-javascript/package.json
e2e/browser/package.json
e2e/node/package.json
package.json
packages/agent/package.json
packages/auth-client/package.json
packages/authentication/package.json
packages/candid/package.json
packages/identity-ledgerhq/package.json
packages/identity/package.json
packages/principal/package.json

Beta release, featuring updated backwards-compatible Principal and auth-client changes

chore: release v1.0.0-beta.0

---

.github/workflows/size-limit.yml
package-lock.json
package.json
packages/identity/package.json
stats.json

test: lowering identity limit from baseline

---

demos/sample-javascript/package.json
e2e/browser/package.json
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/bls-verify/package.json
packages/candid/package.json
packages/identity-secp256k1/.gitignore
packages/identity-secp256k1/.npmignore
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

Resolves a configuration issue with the new `@dfinity/identity-secp256k1` package, addressed in #666

chore: release v0.15.1

---

docs/generated/changelog.html
docs/generated/index.html
packages/identity-secp256k1/package.json

Adds a link to the index of the docs page

docs: links to identity-secp256k1

---

docs/generated/changelog.html
package-lock.json
packages/auth-client/package.json

Moved dev deps out of dependencies for auth-client
Fixes #673 
Covered by existing tests

fix: Moved dev deps out of dependencies for auth-client. resolves #673

---

demos/sample-javascript/package.json
docs/generated/changelog.html
e2e/browser/package.json
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/agent/src/agent/http/http.test.ts
packages/agent/src/agent/http/transforms.ts
packages/assets/package.json
packages/auth-client/package.json
packages/bls-verify/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

Rolls back X-IC-Request-ID header

chore: release v0.15.3

---

.github/workflows/lint.yml
.github/workflows/prettier.yml
docs/generated/changelog.html

chore: updating distro for lint and prettier checks

---

packages/assets/README.md

Added missing event to parameters

docs: example in readme

---

README.md
docs/generated/changelog.html

chore: small copy update for release process

---

demos/sample-javascript/package.json
e2e/browser/package.json
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/bls-verify/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

Bumps minor version due to typo from `JsonnableWebAuthnIdentitiy` type

chore: release v0.16.0

---

demos/sample-javascript/package.json
e2e/browser/package.json
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/bls-verify/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

Version bump to include a couple fixes.

chore: release v0.18.1

---

docs/generated/changelog.html
package-lock.json
package.json
packages/agent/package.json
packages/agent/src/agent/http/http.test.ts
packages/auth-client/FixJSDOMEnvironment.ts
packages/auth-client/jest.config.ts
packages/auth-client/package.json
packages/auth-client/src/__snapshots__/db.test.ts.snap
packages/auth-client/src/db.test.ts
packages/auth-client/test-setup.ts
packages/principal/package.json

fixes node-gyp issues while running npm stall on an M2 mac during development

chore: updating package-lock

---

.github/workflows/e2e-tests.yml
.github/workflows/lint.yml
.github/workflows/mitm.yml
.github/workflows/npm-audit.yml
.github/workflows/prepare-release.yml
.github/workflows/prettier.yml
.github/workflows/publish.yml
.github/workflows/size-limit.yml
.github/workflows/unit-tests.yml
docs/CHANGELOG.md
package-lock.json

Also upgrades github actions to v4

chore: adds required `npm audit` check to PRs

---

README.md
docs/CHANGELOG.md

As requested in https://github.com/dfinity/agent-js/pull/877, this PR adds improved documentation on how to run tests in the `agent-js` repo during local development

docs: adds instructions on how to run unit and e2e tests to the README

---

README.md
bin/update-management-idl.ts
docs/CHANGELOG.md
package-lock.json
package.json
packages/agent/src/actor.ts
packages/agent/src/canisters/management.did
packages/agent/src/canisters/management_idl.ts
packages/agent/src/canisters/management_service.ts

Pulls in the latest management canister interface using didc v0.4.0
Fixes SDK-1707
Existing integration tests

chore: update management canister interface with latest bitcoin features

---

docs/CHANGELOG.md
packages/agent/src/canisters/management.did
packages/agent/src/canisters/management_idl.ts
packages/agent/src/canisters/management_service.ts

Includes methods and types for `sign_with_schnorr`

feat: management canister interface schnorr update

---

packages/candid/README.md

chore: update typo in README.md

---

package-lock.json
packages/identity/package.json
packages/identity/test-setup.ts

`@peculiar/webcrypto` is not a peer dependency of `@dfinity/identity` but a dev dependency.

build: fix @peculiar/webcrypto is no peer dependencies but dev dependencies

---

.github/repo_policies/BOT_APPROVED_FILES
docs/CHANGELOG.md

ci: adds BOT_APPROVED_FILES config

---

.github/workflows/unit-tests.yml

Add Node.js v22 to the unit tests' matrix strategy.
CI

ci: node v22 for unit tests

---

.github/workflows/docs.yml
package.json

Test that the docs build properly on every pull request.
CI passes

ci: test docs builds

---

.github/workflows/size-limit.yml
package.json

Follows up on #1026.
Same tests

ci: use bundle command in size-limit action

---

e2e/node/basic/basic.test.ts

test: re-add removed assertion

---

docs/CHANGELOG.md
e2e/node/package.json
package-lock.json
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.0.0 beta.1

---

e2e/node/basic/assets.test.ts
e2e/node/package.json
e2e/node/tsconfig.json
packages/core/README.md
packages/core/package.json
packages/core/src/assets/index.ts
packages/core/tsconfig.json
pnpm-lock.yaml

feat: remove assets from core package

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.0.0-beta.3

---

pnpm-lock.yaml
pnpm-workspace.yaml

Until `eslint` doesn't patch their dependency, we have to introduce an override.

build: fix audit

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.0.1

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.0.2

---

pnpm-lock.yaml
pnpm-workspace.yaml

Commands executed:
```shell
pnpm audit --fix
pnpm install
```

build: fix pnpm audit

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.2.0

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json
packages/use-auth-client/package.json

chore: release 3.2.1

---

docs/package.json
docs/plugins/package.json
pnpm-lock.yaml

Bumped deps to fix `pnpm audit` report.
Same tests should still pass. Docs build locally.

build: audit fix

---

docs/plugins/package.json
packages/core/package.json
packages/migrate/package.json

Avoid publishing some packages that are not meant to be published (yet) and trigger the release CI again.

chore: release 3.2.2

---

CHANGELOG.md
packages/core/package.json
packages/migrate/package.json
packages/migrate/src/constants.ts
packages/migrate/src/migrator.ts

chore: release 4.0.0

---

docs/src/content/docs/installation.mdx
docs/src/pages/index.astro
packages/migrate/README.md
packages/migrate/package.json

Minor improvements to docs and links.

docs: links and minor improvements

---

.github/CONTRIBUTING.md

Explain the release process for packages.

chore: explain Package Publishing Strategy in the contributing guidelines

---

pnpm-lock.yaml
pnpm-workspace.yaml

build: pnpm audit fix

---

.github/workflows/publish.yml

Trigger v4.0.1 release again. Follow-up of #1129.

chore: release 4.0.1

---

CHANGELOG.md
packages/identity-secp256k1/README.md

docs: fix typo for package submodule

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Removes deprecated/non-existent packages and improves the `build:packages` command.

chore: remove packages from workspace and build command

---

packages/core/package.json

More info at https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

build: make npm know this package has TS declarations

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/core/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

chore: release 4.0.3

---

CHANGELOG.md
package.json
packages/agent/package.json
packages/assets/package.json
packages/auth-client/package.json
packages/candid/package.json
packages/core/package.json
packages/identity-secp256k1/package.json
packages/identity/package.json
packages/principal/package.json

chore: release 4.0.4

---

CHANGELOG.md
packages/candid/src/idl.test.ts
packages/candid/src/idl.ts

Fixes https://github.com/demergent-labs/azle/issues/1526.
Added reproduction code as tests copied from the issue.

fix(candid): recursive type table merging preserves concrete type mapping
